linters-settings:
  lll:
    line-length: 140
  funlen:
    lines: 70

linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - dupl
    - exhaustive
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gosimple
    - govet
    - gosec
    - ineffassign
    - lll
    - misspell
    - nakedret
    - gofumpt
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - prealloc

issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - funlen
        - goconst
        - lll
  exclude-dirs:
    - example
      
service:
  golangci-lint-version: 1.60.3
  prepare:
    - echo "here I can run custom commands, but no preparation needed for this repo"