kafka:
  consumer:
    example1:
      brokers: "staging-confluent-broker-01-earth.trendyol.com:9092"
      topic: eren-test
      groupId: example.groupId
    example2:
      brokers: "staging-confluent-broker-01-earth.trendyol.com:9092"
      topic: eren-test-2
      groupId: example.groupId
      batchConfiguration:
        messageGroupLimit: 2