name: build
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  build:
    name: Lint, Build, and Test
    runs-on: ubuntu-latest
    timeout-minutes: 2
    strategy:
      matrix:
        go-version: [1.21, 1.22, 1.23]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install Dependencies
        run: go mod download
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          args: -c .golangci-lint.yml --timeout=5m -v
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...